#### [Nguyễn Trọng Tuấn - 20176898](https://www.facebook.com/ISantaPo)
$\alpha = 0.23 ,\space \beta = 0.11$ 

#### Câu 1:
\begin{align*}
\mathbb{P} = 
    \begin{bmatrix}
    1/2 & 1/2 & 0 \\
    1/3 & 1/3 & 1/3 \\
    1/6 & 1/2 & 1/3
    \end{bmatrix}
\end{align*}

Phân phối dừng $\pi$ phải thỏa mãn 2 điều kiện là:
\begin{align*}
    \begin{cases}
    \pi \mathbb{P} = \pi \\
    \sum_i \pi_i = 1
    \end{cases}
\end{align*}

Xét điều kiện đầu tiên: $\pi \mathbb{P} = \pi$  
Giải hệ phương trình tuyến tính ta được:  

\begin{align*}
\pi ^T = 
    \begin{bmatrix}
    5/14 \\
    3/7 \\
    3/14
    \end{bmatrix}
\end{align*}

Ta thấy $\pi$ thoả mãn điều kiện thứ 2, suy ra $\pi = (\frac{5}{14},\frac{3}{7},\frac{3}{14})$ là phân phối dừng của ma trận chuyển $\mathbb{P}$  

#### Câu 2:
\begin{align*}
\mathbb{P} = 
    \begin{bmatrix}
    0 & 0 & 0.23 & 0 & 0 & 0 & 0.77 \\
    0 & 0.89 & 0 & 0 & 0.11 & 0 & 0 \\
    0 & 0 & 0.8 & 0 & 0 & 0.2 & 0 \\
    0 & 0.3 & 0.4 & 0.3 & 0 & 0 & 0 \\
    0 & 0.5 & 0 & 0 & 0.2 & 0 & 0.3 \\
    0 & 0 & 0.23 & 0 & 0 & 0.77 & 0 \\
    0 & 0.5 & 0 & 0 & 0 & 0 & 0.5 \\
    \end{bmatrix}
\end{align*}

*(a)*  
![ex2_3](graph.png)

Từ đồ thị ta có thể chia thành các phân lớp là $\{0\},\{3\},\{2,5\},\{1,4,6\}$  

*(b)*  
Dễ dàng thấy $d(0) = d(3) = 1$  

Xét phân lớp $\{2,5\}$ có $P_22 > 0$ và $P_22^{(2)} > 0$ nên $d(2) = d(5) = 1$

Tương tự với phân lớp $\{1,4,6\}$ ta được $d(1) = d(4) = d(6) = 1$
#### Câu 3:
\begin{align*}
\mathbb{P} = 
    \begin{bmatrix}
    0.22 & 0.26 & 0.26 & 0.26 \\
    89/300 & 0.11 & 89/300 & 89/300 \\
    67/300 & 67/300 & 0.33 & 67/300 \\
    0.22 & 0.22 & 0.22 & 0.34
    \end{bmatrix}
    ; \space
\lambda = 
    \begin{bmatrix}
    0.1 \\
    0.3 \\
    0.4 \\
    0.2
    \end{bmatrix}
\end{align*}

*(a)*  
Phân phối thị phần của tháng tiếp theo được tính theo công thức:

\begin{align*}
\lambda^{(1)} = \lambda \mathbb{P} = (\frac{733}{3000},\frac{577}{3000},\frac{291}{1000},\frac{817}{3000})
\end{align*}

*(b)*  
Tìm phân phối dừng, trước tiên ta giải hệ phương trình tuyến tính $\pi \mathbb{P} = \pi$   

Ta được $\pi = (0.23683203, 0.20756066, 0.2757149 , 0.2798924)$  thỏa mãn điều kiện thứ hai  

Suy ra $\pi = (0.23683203, 0.20756066, 0.2757149 , 0.2798924)$ là phân phối dừng  

#### Câu 4:

In [77]:
import numpy as np
import math

def period_i(i,P,):
    d = []
    for k in range(1,100):
        P = P.dot(P)
        if (P[i,i]):
            d.append(k)
    return math.gcd(d)

#### Câu 5:

In [98]:
def computePi(P):
    if P.shape == (1,1):
        return 1
    
    size = P.shape[0]
    dP = P.T - np.identity(size)
    A = np.append(dP,np.ones(size)).reshape(size+1,size)
    b = np.append(np.zeros(size),1)
    
    return np.linalg.solve(A.T.dot(A),A.T.dot(b))

In [13]:
import numpy as np

P = np.array([[0.2,0.7,0.1],
             [0.4,0.5,0.1],
             [0.2,0.8,0]])

In [14]:
PI = np.transpose(P-np.eye(len(P)))
PI

array([[-0.8,  0.4,  0.2],
       [ 0.7, -0.5,  0.8],
       [ 0.1,  0.1, -1. ]])

In [15]:
C = []
for i in range(len(P)-1):
    C = np.r_[C,PI[i,:]]


In [16]:
C

array([-0.8,  0.4,  0.2,  0.7, -0.5,  0.8])

In [8]:
C=np.r_[C,np.zeros(len(P))+1]
D=C.reshape(3,3)

array([-0.8,  0.4,  0.2,  0.7, -0.5,  0.8,  1. ,  1. ,  1. ])

In [11]:
np.r_?

Type:        RClass
String form: <numpy.lib.index_tricks.RClass object at 0x7f75845ad210>
Length:      0
File:        ~/anaconda3/lib/python3.7/site-packages/numpy/lib/index_tricks.py
Docstring:  
Translates slice objects to concatenation along the first axis.

This is a simple way to build up arrays quickly. There are two use cases.

1. If the index expression contains comma separated arrays, then stack
   them along their first axis.
2. If the index expression contains slice notation or scalars then create
   a 1-D array with a range indicated by the slice notation.

If slice notation is used, the syntax ``start:stop:step`` is equivalent
to ``np.arange(start, stop, step)`` inside of the brackets. However, if
``step`` is an imaginary number (i.e. 100j) then its integer portion is
interpreted as a number-of-points desired and the start and stop are
inclusive. In other words ``start:stop:stepj`` is interpreted as
``np.linspace(start, stop, step, endpoint=1)`` inside of the brackets.
Aft

In [12]:
np.r_[np.array([1,2,3]), 0, 0, np.array([4,5,6])]

array([1, 2, 3, 0, 0, 4, 5, 6])